"""initial schema

Revision ID: 52d6f57f0a6d
Revises: 
Create Date: 2026-03-03 15:04:59.832941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d6f57f0a6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('movement_type', sa.Enum('barbell', 'dumbbell', 'kettlebell', 'bodyweight', 'machine', 'cardio', 'other', name='movementtype'), nullable=True),
    sa.Column('is_named_benchmark', sa.Boolean(), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('muscle_groups', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    op.create_index(op.f('ix_movements_name'), 'movements', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authentik_sub', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('weight_unit', sa.Enum('lbs', 'kg', name='weightunit'), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authentik_sub'), 'users', ['authentik_sub'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('workout_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('parse_flagged', sa.Boolean(), nullable=True),
    sa.Column('parse_method', sa.Enum('ollama', 'claude', 'regex', name='parsemethod'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_days_date'), 'workout_days', ['date'], unique=True)
    op.create_index(op.f('ix_workout_days_id'), 'workout_days', ['id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_day_id', sa.Integer(), nullable=False),
    sa.Column('track_type', sa.Enum('fitness_performance', 'endurance', name='tracktype'), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('selected_option', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_day_id'], ['workout_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_logs_id'), 'workout_logs', ['id'], unique=False)
    op.create_table('workout_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_day_id', sa.Integer(), nullable=False),
    sa.Column('track_type', sa.Enum('fitness_performance', 'endurance', name='tracktype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_day_id'], ['workout_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_tracks_id'), 'workout_tracks', ['id'], unique=False)
    op.create_table('workout_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('block_type', sa.Enum('strength', 'accessory', 'conditioning_amrap', 'conditioning_emom', 'conditioning_fortime', 'conditioning_interval', 'pump', 'other', name='blocktype'), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['workout_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_blocks_id'), 'workout_blocks', ['id'], unique=False)
    op.create_table('conditioning_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('amrap', 'for_time', 'emom', 'interval', 'tabata', name='conditioningformat'), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('time_cap_minutes', sa.Float(), nullable=True),
    sa.Column('is_partner', sa.Boolean(), nullable=True),
    sa.Column('is_named_benchmark', sa.Boolean(), nullable=True),
    sa.Column('benchmark_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['workout_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditioning_workouts_id'), 'conditioning_workouts', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.String(length=10), nullable=True),
    sa.Column('rpe_min', sa.Float(), nullable=True),
    sa.Column('rpe_max', sa.Float(), nullable=True),
    sa.Column('percent_1rm_min', sa.Float(), nullable=True),
    sa.Column('percent_1rm_max', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_alternative', sa.Boolean(), nullable=True),
    sa.Column('alternative_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['workout_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_table('conditioning_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conditioning_workout_id', sa.Integer(), nullable=False),
    sa.Column('interval_order', sa.Integer(), nullable=True),
    sa.Column('modality', sa.Enum('bike_erg', 'run', 'row', 'ski', 'other', name='modality'), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('effort_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conditioning_workout_id'], ['conditioning_workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditioning_intervals_id'), 'conditioning_intervals', ['id'], unique=False)
    op.create_table('conditioning_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('conditioning_workout_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.Enum('rounds_reps', 'time', 'load', 'distance', name='resulttype'), nullable=True),
    sa.Column('rounds_completed', sa.Integer(), nullable=True),
    sa.Column('reps_completed', sa.Integer(), nullable=True),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_reps', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_named_benchmark', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conditioning_workout_id'], ['conditioning_workouts.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['workout_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditioning_results_id'), 'conditioning_results', ['id'], unique=False)
    op.create_table('exercise_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('sets_completed', sa.Integer(), nullable=True),
    sa.Column('reps_per_set', sa.JSON(), nullable=True),
    sa.Column('weight_per_set_lbs', sa.JSON(), nullable=True),
    sa.Column('weight_per_set_kg', sa.JSON(), nullable=True),
    sa.Column('tempo_used', sa.String(length=10), nullable=True),
    sa.Column('rpe_actual', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['workout_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_results_id'), 'exercise_results', ['id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('one_rm', 'three_rm', 'five_rm', 'max_reps', 'max_weight_reps', 'best_time', name='recordtype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('set_count', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exercise_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_result_id'], ['exercise_results.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_records_id'), 'personal_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_records_id'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index(op.f('ix_exercise_results_id'), table_name='exercise_results')
    op.drop_table('exercise_results')
    op.drop_index(op.f('ix_conditioning_results_id'), table_name='conditioning_results')
    op.drop_table('conditioning_results')
    op.drop_index(op.f('ix_conditioning_intervals_id'), table_name='conditioning_intervals')
    op.drop_table('conditioning_intervals')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_conditioning_workouts_id'), table_name='conditioning_workouts')
    op.drop_table('conditioning_workouts')
    op.drop_index(op.f('ix_workout_blocks_id'), table_name='workout_blocks')
    op.drop_table('workout_blocks')
    op.drop_index(op.f('ix_workout_tracks_id'), table_name='workout_tracks')
    op.drop_table('workout_tracks')
    op.drop_index(op.f('ix_workout_logs_id'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_workout_days_id'), table_name='workout_days')
    op.drop_index(op.f('ix_workout_days_date'), table_name='workout_days')
    op.drop_table('workout_days')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_authentik_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_movements_name'), table_name='movements')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_table('movements')
    # ### end Alembic commands ###
